package brenay.vgasoc.board.olimex.gatemate_a1_evb

import spinal.core._
import spinal.lib.{BufferCC, ResetCtrlFiber}

import brenay.lib.blackbox.cologne.gatemate.{CcBufG, CcPll, PerfMode}
import brenay.vgasoc.VgaSettings

/** Area to generate the clock domains and reset for the VgaSoc
  *
  * There are 3 clock domains:
  *
  *   - processing, at the speed targeted by the designer of the accelerator/
  *     cpu/state machine what will process (graphical or not)
  *   - extMems, very pipelined to reach the fmax of the external memories
  *     (PRSRAM and FLASH), to have maximum burst bandwidth
  *   - optional graphic, clocked at the VGA speed needed by the settings vgaSettings
  *
  * There is two different resets. The `configResetCtrl.reset` is generated when the
  * bitstream is loaded into the FPGA and can occur at power-on or when the RST_N
  * pin is driven low. It is intended to hold until the PLL are locked, and
  * the electrical condition are met (ideally power good, external crystal stability, etc.).
  *
  * `systemResetCtrl.reset` is generated by the MCU, an IO or by the config reset.
  * It resets the processing, extMem and graphic domains, but not the
  * debug domain. This way a system reset do not reset the debug infrastructure,
  * as mandated by the RISC-V Debug Spec. It insure that that these clock domains
  * have sufficient reset clock counts regardless of the frequencies choices.
  * The exit of resets is also done quasi-simultaneously, and synchronized to each
  * clock domains with BufferCC.
  */
class SocCtrl(
    val processingFrequency: HertzNumber,
    val extMemsFrequency: HertzNumber,
    val withGraphic: Boolean = true,
    val vgaSettings: VgaSettings = VgaSettings(),
    val withDebug: Boolean = true
) extends Component {
  val io = new Bundle {
    val externalClock = in Bool ()
    val externalResetN = in Bool ()
    val systemResetFromMcu = withDebug generate (in Bool ())
  }

  val refClockFrequency = 10 MHz

  val processingPll = new CcPll(refClockFrequency, processingFrequency, PerfMode.Speed)
  val extMemsPll = new CcPll(refClockFrequency, extMemsFrequency, PerfMode.Speed)

  val graphicFrequency = vgaSettings.verticalFrequency
  val graphicPll =
    withGraphic generate new CcPll(refClockFrequency, graphicFrequency, PerfMode.Speed)

  // Use the external clock with BOOT (will generate .INIT() in DFF primitives)
  // for the reset generation RTL.
  val resetsGeneration = new ClockingArea(
    ClockDomain(
      io.externalClock,
      frequency = FixedFrequency(refClockFrequency),
      config = ClockDomainConfig(
        resetKind = BOOT
      )
    )
  ) {

    val configResetCtrl = new ResetCtrlFiber()
    configResetCtrl.enableBootReset()

    // Add resets until PLL locked.
    val systemDomainResetDurations =
      (for (pll <- Seq(processingPll, extMemsPll, graphicPll).filter(_ != null)) yield {
        pll.io.clkRef <> io.externalClock
        pll.io.usrClkRef := False
        pll.io.clkFeedback := False
        pll.io.usrLockedStdyRst := False

        // the PLLs are all in the same clock domain, so the locked is sync and relaxed
        configResetCtrl.addSyncRelaxedReset(pll.io.usrPllLocked, LOW)
        pll.outClk.toTime.toDouble * 64
      })

    // U2 is a HX7027 2.7 V voltage detector with open drain output on the
    // RST_N config reset. Its input is connected to +3V3 with a 10K/22uF with
    // tau=220 ms, noted as 370 ms reset delay. So the reset part like
    // the crystal oscillator SX5M10.000M20F30T (5 ms startup in spec) are
    // good without any other delays.
    val configResetDuration =
      (systemDomainResetDurations).max

    // Use minimum power of 2 (for CPE efficiency) for the slowest clock domain
    // to reset properly.
    configResetCtrl.holdCycles = (1 << log2Up(
      (configResetDuration * refClockFrequency.toDouble).ceil.toInt
    ))

    val systemResetCtrl = new ResetCtrlFiber()
    systemResetCtrl.enableBootReset()
    systemResetCtrl.addSyncRelaxedReset(configResetCtrl.reset, HIGH)

    systemResetCtrl.addAsyncReset(io.externalResetN, LOW)

    if (withDebug) systemResetCtrl.addAsyncReset(io.systemResetFromMcu, HIGH)
    systemResetCtrl.holdCycles = (1 << log2Up(
      (systemDomainResetDurations.max.toDouble * refClockFrequency.toDouble).ceil.toInt
    ))

    val processing = new Area {
      val clkBufG = new CcBufG()
      clkBufG.io.i := processingPll.io.clk0
      val clk = clkBufG.io.o

      // The reset flip-flop synchronizer should use the output clock, but be
      // reset at bitstream load.
      val rstGeneration = new ClockingArea(
        ClockDomain(
          clk,
          config = ClockDomainConfig(
            resetKind = BOOT
          )
        )
      ) {
        val rst = BufferCC(systemResetCtrl.reset, init = True)
      }

      val clockDomain = ClockDomain(
        clk,
        rstGeneration.rst,
        config = ClockDomainConfig(
          resetKind = SYNC,
          resetActiveLevel = HIGH
        ),
        frequency = FixedFrequency(processingFrequency)
      )
    }

    val debug = withDebug generate new Area {
      val clk = processing.clk

      // The reset flip-flop synchronizer should use the output clock, but be
      // reset at bitstream load.
      val rstGeneration = new ClockingArea(
        ClockDomain(
          clk,
          config = ClockDomainConfig(
            resetKind = BOOT
          )
        )
      ) {
        val rst = BufferCC(configResetCtrl.reset, init = True)
      }

      val clockDomain = ClockDomain(
        clk,
        rstGeneration.rst,
        config = ClockDomainConfig(
          resetKind = SYNC,
          resetActiveLevel = HIGH
        ),
        frequency = FixedFrequency(processingFrequency)
      )
    }

    val extMems = new Area {

      val clkBufG = new CcBufG()
      clkBufG.io.i := extMemsPll.io.clk0
      val clk = clkBufG.io.o

      // The reset flip-flop synchronizer should use the output clock, but be
      // reset at bitstream load.
      val rstGeneration = new ClockingArea(
        ClockDomain(
          clk,
          config = ClockDomainConfig(
            resetKind = BOOT
          )
        )
      ) {
        val rst = BufferCC(systemResetCtrl.reset, init = True)
      }

      val clockDomain = ClockDomain(
        clk,
        rstGeneration.rst,
        config = ClockDomainConfig(
          resetKind = SYNC,
          resetActiveLevel = HIGH
        ),
        frequency = FixedFrequency(extMemsFrequency)
      )
    }

    val graphic = withGraphic generate new Area {

      val clkBufG = new CcBufG()
      clkBufG.io.i := graphicPll.io.clk0
      val clk = clkBufG.io.o

      // The reset flip-flop synchronizer should use the output clock, but be
      // reset at bitstream load.
      val rstGeneration = new ClockingArea(
        ClockDomain(
          clk,
          config = ClockDomainConfig(
            resetKind = BOOT
          )
        )
      ) {
        val rst = BufferCC(systemResetCtrl.reset, init = True)
      }

      val clockDomain = ClockDomain(
        clk,
        rstGeneration.rst,
        config = ClockDomainConfig(
          resetKind = SYNC,
          resetActiveLevel = HIGH
        ),
        frequency = FixedFrequency(graphicFrequency)
      )
    }
  }

  val processingClockDomain = resetsGeneration.processing.clockDomain
  val extMemsClockDomain = resetsGeneration.extMems.clockDomain
  val graphicClockDomain = if (withGraphic) resetsGeneration.graphic.clockDomain else null
  val debugClockDomain = if (withDebug) resetsGeneration.debug.clockDomain else null

}
