# ExplicitResultTypes is not used because it's too verbose with spinalHDL
rules = [
  DisableSyntax
  RemoveUnused
  NoAutoTupling
  NoValInForComprehension
  ProcedureSyntax
  RedundantSyntax
  OrganizeImports
]

DisableSyntax {
  noFinalize = true
  noXml = true # legacy inline xml
  noFinalVal = true # because break incremental compilation
}

OrganizeImports {
  blankLines = Auto
  coalesceToWildcardImportThreshold = 1000
  expandRelative = false
  groupSeparately = []
  groupedImports = Merge
  groups = [
    "spinal."
    "re:(javax?|scala)\\."
    "*"
]
  importSelectorsOrder = Ascii
  importsOrder = Ascii
  preset = DEFAULT
  removeUnused = true
}