version = 3.11.1
runner.dialect = scala212
align.preset = some
maxColumn = 100
docstrings.wrap = no

// this does not work with formatOnSave in vscode with metals server 1.6.8
project.excludePaths = [
  "glob:ext/**"
]